### ISSUE TITLE
Broken loot tables

### ISSUE THREAD

**Issue by modsbydreamCritting** [nudelauflauch/shutter#11]
Version used: 2.0.2 1.20.1 Forge

Several loot tables fail to load, giving Json Syntax Exceptions

To find errors see [https://mclo.gs/ffiAxZe](https://mclo.gs/ffiAxZe) lines 10635, 10957, 11166, 11556, 11974, 12078, 12286, 12338, 12651 and 12703 (or just use f3 and search)

**Comment by nudelauflauch** [comment]
Could you download the [](https://cdn.modrinth.com/data/NjHNA0vG/versions/kgn7EQTl/shutter-2.0.4-fabric-1.20.4.jar)

**Comment by modsbydreamCritting** [comment]
Newest update is for Fabric so would not be compatible with the modpack where the errors were found (MineColonies: Dimensional Adventure) it's not a major issue just causes some log spam.

**Comment by nudelauflauch** [comment]
My brother will update the mod soon. If you want you can download it from Cursforge where it should always be updated

**Comment by Barerock** [comment]
This still is not fixed, I use this mod and it always spams loot table errors on world join.

**Comment by Barerock** [comment]
[Error text.txt](https://github.com/user-attachments/files/15975551/Error.text.txt)
Dozens of these occur, and this is one that's always present between profiles.

**Comment by nudelauflauch** [comment]
Would you mind sharing the full log file and the specific mod version and mod list that you are using

**Comment by Barerock** [comment]
Shore:
shutter-2.0.4-1.20.1.jar
[A-ModList.txt](https://github.com/user-attachments/files/15994110/A-ModList.txt)
[2024-06-25-6.log.gz](https://github.com/user-attachments/files/15994165/2024-06-25-6.log.gz)

**Comment by nudelauflauch** [comment]
I have found the error and uploaded it to curseforge. It should be uploaded soon to modrinth.
