### ISSUE TITLE
Crash with Effortless Building

### ISSUE THREAD

**Issue by WenXin20** [nudelauflauch/shutter#12]
Minecraft v1.20.1
Forge v47.2.20
[Effortless Building](https://www.curseforge.com/minecraft/mc-mods/effortless-building) v3.8
Shutters v2.0.2

When placing the shutters using Effortless Building, the game crashes. Hold down alt to choose the building mode.
[Crash Report](https://gist.github.com/WenXin20/e9fa87de78e3003de7ae2b7f1a4a0097)

**Comment by nudelauflauch** [comment]
I found the error and it will be fixed in an upcoming update
