### ISSUE TITLE
Unable to open Gold Shutter

### ISSUE THREAD

**Issue by Jack-Chronicle** [nudelauflauch/shutter#14]
Minecraft 1.20.4
Fabric 0.15.11
Shutters 2.0.4

When right clicking the gold shutter, nothing happens. Tried powering with redstone, and also nothing
If you attach another Shutter type and power or right click that one, then the attached gold shutter will also open but that seems to be the only way I can open it

**Comment by nudelauflauch** [comment]
Thanks for the bug report. I found the error and uploaded it on curseforge. The bugfix should be uploaded in the following days on modrinth too.
