### ISSUE TITLE
Shutters don't break attaching blocks.

### ISSUE THREAD

**Issue by Zeykehasnt** [nudelauflauch/shutter#16]
It's not a straight up bug, but it's just inconsistent with vanilla trapdoors and doors. 
![image](https://github.com/user-attachments/assets/c6ff6b9b-4a9b-426b-8b24-3c744e86b6a1)

**Comment by nudelauflauch** [comment]
Thanks for reporting it. I fixed it and it should be in the newest update 2.1.3

**Comment by Zeykehasnt** [comment]
That's cool. You don't support 1.20.1 anymore?

**Comment by Zeykehasnt** [comment]
@nudelauflauch I apologize.

**Comment by nudelauflauch** [comment]
Its alright. I will update 1.20.1 for forge.
