### ISSUE TITLE
Iron and Netherite Shutters missing animations

### ISSUE THREAD

**Issue by Devilswarchild** [nudelauflauch/shutter#7]
shutters version 2.0.2-1.20.1
mc 1.20.1
forge version 47.2.20

so all the shutters open and close like they are supposed to except for the iron and netherite versions. can we please get this fixed?

![image](https://github.com/nudelauflauch/shutter/assets/27385258/0783ab51-2126-48a6-8da2-6589c9defb98)

**Comment by nudelauflauch** [comment]
The iron shutters can just be opened with redstone as in vanila as well as the netherite shutter. We will try change the behavior to be more closer to the quark behavior.
