### ISSUE TITLE
Axes stop mining axeable blocks faster with mod installed, due to problem with tags

### ISSUE THREAD

**Issue by megatrook** [nudelauflauch/shutter#9]
i was playing in my singleplayer world and noticed i couldn't mine logs and such with my axe or paxel, which led me to some googling to find the problem. installing Load My F***ing Tags fixed the issue, and now i can mine logs and such faster again.

here is my log! (line 2121 is where the error appears) https://mclo.gs/OPLbsCB#L482

**Comment by nudelauflauch** [comment]
does this crash your game or are these just errors

**Comment by megatrook** [comment]
it doesn't crash my game! just the axes didn't work

**Comment by nudelauflauch** [comment]
I uploaded to curseforge a new version wich should fix this bug
